name: Release verification

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  verify_proofs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup ocaml, and caching
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.4.1"

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Run standard test suite (alcotest + qcheck)
        run: opam exec -- dune runtest
