name: OCaml CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0 
          dune-cache: true

      - name: Install dependencies
        run: |
          opam update
          opam install . --deps-only --with-test --with-doc
          opam install ocamlformat

      - name: Fix and Check Code Formatting
        run: |
          opam exec -- dune fmt
          opam exec -- dune build @fmt --auto-promote

      - name: Build project
        run: opam exec -- dune build

      - name: Run test suite
        run: opam exec -- dune runtest