name: Commit check

on:
  push:
    branches: [ main ]
    paths:
      - 'calc/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'calc/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: setup ocaml and caching
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.4.1"

      - name: install dependencies
        run: opam install ./calc --deps-only --with-test

      - name: run standard test suite (alcotest + qcheck)
        run: opam exec -- dune runtest --root calc